name: 'CI'

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Use Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Packages
        run: yarn install
      - name: Linting & Formatting
        run: yarn analyze:ci
      - name: Type Checking
        run: yarn analyze:types
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Use Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Packages
        run: yarn install
      - name: Test
        run: yarn test
      - id: runActionValid
        name: Try Valid URL
        uses: ./
        with:
          domain: https://joggr.io
          expiration_days: 7
      - id: runActionInvalid
        name: Try Invalid URL
        uses: ./
        with:
          domain: https://not-a-real-domain-at-all-1382712984.com
          expiration_days: 7
      - id: invalidActionStatus
        name: Invalid URL Status
        if: steps.runActionInvalid.outputs.error_message == ''
        run: exit 1
